package com.shaulin.crud.controllers;

import com.shaulin.crud.model.Product;
import com.shaulin.crud.repositories.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/products")
public class ProductController {

    @Autowired  // This means to get the bean called productRepository
    // Which is auto-generated by Spring, we will use it to perform database operations.
    ProductRepository repository;

    @GetMapping
    public ResponseEntity getAll() {
        List<Product> ListProducts = repository.findAll();
        /* A linha abaixo usa o ResponseEntity para fazer com que ele retorne uma retorne uma resposta do tipo OK (Código 200)
        Além disso o o corpo dessa reposta será a lista de produtos cadastrados na base
         */
        return ResponseEntity.status(HttpStatus.OK).body(ListProducts);
    }
}
